spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-2w7iaqz0uo3z838c.us.auth0.com/.well-known/jwks.json
          issuer-uri: https://dev-2w7iaqz0uo3z838c.us.auth0.com

jwt:
  secret: ${JWT_SECRET:NnV0kJy/2t68gxPh1P5tH3u5V85NYghUJ5D9yRTfIoE=}
  refreshSecret: ${JWT_REFRESH_SECRET:qIqUBt3FdlfCzMoQybU9lkndm0G2C93DD/4lAhMTFYw=}

okta:
  oauth2:
    issuer: https://dev-2w7iaqz0uo3z838c.us.auth0.com
    client-id: KNr7Y3xwMAC4l2krfuX3OXe9kSZqDNsl
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET:xJ4j2y9ZfyG3xJgQ5sQwH+lhmS3IoV2Rg0u/tTzS/Ks=}

server:
  port: 8080
