spring:
  datasource:
    url: jdbc:postgresql://qa-db-host:5432/postgres_qa
    username: qa_user
    password: qa_password

jwt:
  secret: qa-secret-key

cors:
  allowed-origins: "https://qa.example.com"
